const history = {
  tab_forro: 'Historia del Forró',
  tab_school: 'Forró Arrasta-pé Sevilla',
  tab_elton: 'Profesor Elton Rodrigues',
  
  // Original Forró Intro
  forro_subtitle: 'Orígenes y Evolución',
  forro_p1: 'El forró es mucho más que un ritmo; es el alma del Nordeste de Brasil. Nacido en las zonas rurales, evolucionó de bailes tradicionales como el xote, el xaxado y el baião.',
  forro_p2: 'Su expansión mundial comenzó con el legendario Luiz Gonzaga, el "Rey del Baião", quien llevó el sonido del acordeón, la zabumba y el triángulo a todos los rincones de Brasil. Hoy en día, el forró es una danza de conexión internacional que une a personas de todas las culturas.',
  forro_quote: '"El forró es una fiesta de alegría, donde el único idioma es el abrazo."',

  // Forró History (New Content)
  forro_what_title: '¿Qué es el forró?',
  forro_what_p1: 'El Forró es un género musical y una danza brasileña que proviene originalmente del nordeste de Brasil en la región de Recife, estado de Pernambuco, pero con influencias de Europa y África. En Brasil es símbolo de la Fiesta de San Juan. Hoy en día, el Forró se ha expandido por varios continentes teniendo festivales de gran magnitud donde se encuentran personas de diversos países.',
  
  forro_origin_title: 'Origen del término “Forró”',
  forro_origin_p1: 'El origen de la palabra Forró es controvertido. Una versión defendida por el historiador y escritor Luís da Câmara Cascudo, dice que la palabra proviene de la abreviatura de forrobodó que empezó a ser introducida en Brasil a partir de la segunda mitad del siglo XlX, y que significa fiesta popular, baile festanza, diversión, raleo (bagunça), bromas (brincadeiras, juego con el otro) confusión, desorden y fue bastante utilizada por la prensa y según Pereira da Costa también con el significado de diversión y fiesta.',
  forro_origin_p2: 'Según los historiadores y escritores Luís da Câmara Cascudo (1952), Reinaldo Pimenta (2002), Carlos Marcelo y Rosualdo Rodrigues (2012) y varios otros investigadores de la lengua portuguesa en Brasil, la palabra forrobodó es etimológicamente derivada de la palabra FAUX-BOURDON.',
  forro_origin_p3: 'Francia siglo XV, “falso bordón" es una técnica de armonización musical usada en la alta edad media y bajo renacimiento por compositores de la escuela franco-flamenca y era particularmente utilizada en las composiciones de músicas litúrgicas. Guillaume Dufay fue un destacado practicante de esta forma de componer. A través de la escuela franco-flamenca, la palabra se incorporó en el lenguaje gallego-portugués transformándose en FORBODÓ en Portugal (siglo XVlll), llegando al Brasil con una tercera modificación convirtiéndose en FORROBODÓ en el siglo XlX. Al principio, el término significaba apenas la fiesta y el local donde se realizaba, pasando después a significar también el género musical y la danza.',
  forro_origin_p4: 'Otra versión inventada por populares y sin comprobación gramatical en la lengua portuguesa para el significado de la palabra Forró vino del mal entendimiento de la expresión inglesa for all (para todos), en alusión a las fiestas que tenían lugar en el mes de junio en las haciendas de algunos terratenientes británicos. Fue en 1873 cuando la compañía Great Western consiguió la concesión para construir una ferrovía en Pernambuco que haría la conexión entre las ciudades de Recife y Limoeiro. Así, según dicha versión, los ingleses invitaban a bailar a los obreros en las haciendas, popularizando así su expresión.',
  
  forro_how_title: '¿Cómo se baila Forró?',
  forro_how_p1: 'El Forró se baila en parejas en una posición de abrazo cerrado, con los compañeros uno frente al otro, utilizando un contacto corporal total o parcial, moviendo con gran cadencia el cuerpo. Dependiendo del estilo de música que se toque -baião, xote, xaxado, forró universitario o electrónica- la forma de bailar también cambia, adaptando la cadencia y los movimientos.',
  forro_how_p2: 'Pasos básicos: se baila en pareja con tiempo binario, o sea, dos tiempos a la derecha, dos tiempos a la izquierda o dos tiempos hacia adelante y dos tiempos hacia atrás.',
  forro_how_p3: 'Figuras: Son pasos realizados con los brazos y con las piernas fuera de la estructura de los pasos básicos.',

  forro_rhythms_title: 'Ritmos que componen el Forró',
  forro_rhythms_p1: 'Del batuque surgieron diversas variantes que se difundieron tanto en zonas urbanas como rurales bajo diversos nombres y estilos según la región del país. El forró es una de estas variantes, subdividiéndose a su vez en otras ramas musicales y de danza como el xote, baião, arrastapé, xaxado, el côco, maracatu, la quadrilha junina (marchinha), la samba rural, amazurca, la rancheira…etc.',
  forro_rhythms_p2: 'El Baião tiene su origen en el siglo XIX en el nordeste del país, pero faltan informaciones detalladas para su inicio concreto. Según algunos investigadores la palabra proviene de “baiano”. La danza procedía del Lundú y se bailaba en círculos en los cuales uno de los presentes invitaba con una ombligada a los demás integrantes a bailar. Esta forma de bailar presenta diferencias regionales y de época. El baião tradicional de Pernambuco es tocado con acordeón, triángulo y zabumba.',
  forro_rhythms_p3: 'El Xote, género de origen europeo que surge de los salones aristocráticos en la época de la Regencia (finales del siglo XIX). Conocido originalmente como schottisch, predominó en el período del segundo reinado, incorporándose posteriormente a las funciones urbanas populares, pasando a denominarse chotis y finalmente xote.',
  forro_rhythms_p4: 'Xaxado, proviene del sonido que hacían los zapatos en el suelo al bailar; Es un baile del interior, bailado sólo por hombres, que se remonta a la década de los años 20. El acompañamiento era puramente vocal, melodía sencilla, ritmo ligero y letras agresivas y satíricas. Se hizo popular entre los bandidos del grupo Lampião.',
  forro_rhythms_p5: 'El Coco, danza circular del norte y nordeste de Brasil, fusión de musicalidad negra y cabocla.',
  
  forro_diffusion_title: 'Difusión del nordeste para el mundo',
  forro_diffusion_p1: 'Luiz Gonzaga (13 de diciembre de 1912, Exu, Pernambuco, Brasil - 2 de agosto de 1989, Recife, Pernambuco, Brasil) fue el principal difusor de ritmo nordestino empezando a finales de la década de 1940, seguido por Jackson do Pandeiro (31 de agosto de 1919, Paraíba, Brasil - 10 de jullo de 1982, Brasília, Distrito Federal, Brasil), Sebastião Jacinto da Silva, de nombre artístico Jacinto Silva (23 de agosto de 1933, Palmeira dos Índios, Alagoas, Brasil - 19 de febrero de 2001, Caruaru, Pernambuco, Brasil) y varios otros cantantes y compositores dieron gran visibilidad y popularización del ritmo en todo el país. Además de ellos, cantantes como Carmélia Alves (14 de febrero de 1923, Río de Janeiro, Brasil – 2/3 de noviembre de 2012, Río de Janeiro, Brasil) que recibió la titulación de reina del baião (Rainha do Baião) del propio Luiz Gonzaga, Marinês (Inês Caetano de Oliveira, 16 de noviembre de 1935, São Vicente Férrer, Pernambuco, Brasil - 14 de mayo de 2007, Recife, Brasil), Claudette Soares (31 de octubre de 1937, Rio de Janeiro, Rio de Janeiro, Brasil – actualidad).',
  forro_diffusion_p2: 'Nació en el nordeste brasileño y fue llevado para el mundo, pasó a ser un género típico de los festejos juninos, pero es bailado en todas las épocas del año.',
  
  forro_instruments_title: 'Instrumentos tradicionales',
  forro_instruments_p1: 'Los instrumentos utilizados en el forró tradicional, llamado “Forró pé-de-serra”, son el Acordeón, cuyo teclado es recorrido enteramente, la Zabumba y el Triángulo. Aunque en la actualidad existen variantes que incorporan otros instrumentos mezclando las raíces europeas con las autóctonas.',
  forro_instruments_p2: 'En la década de 1990, el ritmo y el baile fueron muy influenciados por la lambada, la salsa y el tango.',

  school_subtitle: 'Proyecto Forró Arrasta-pé Sevilla',
  school_p1: 'Forró Arrasta-pé Sevilla empezó en 2010 como un proyecto de integración cultural a través de los elementos de la cultura popular brasileña, en este caso, el Forró, y desde entonces, hace parte de la escena cultural de Brasil en Sevilla y en varias partes de Europa.',
  school_p2: 'Elton Rodrigues es el organizador y mentor de este proyecto que está fundamentado principalmente por el estilo Forró Pé de Serra y Universitario. Tiene una metodología propia de enseñanza, desarrollada a través de los años de práctica y enseñanza, influenciada por la danza de salón, pero fundamentada en las bases nordestinas.',
  school_p3: 'En las aulas de Forró Arrastapé Sevilla se difunden los distintos movimientos de base y figuras, con el objetivo de que el bailarín y la bailarina, después de aprender las bases, busquen sus propias formas de expresión, improvisación y sean capaces de crear sus propias secuencias de movimientos con total libertad.',
  elton_role: 'Instructor Maestro & Fundador',
  elton_bio: 'Elton Rodrigues, brasileño, nació en la ciudad de Vespasiano y residió posteriormente en Lagoa Santa y Belo Horizonte, en el estado de Minas Gerais, Brasil. Consagrado hoy como el gran referente y el mejor maestro de Forró en Sevilla, su primer contacto con la cultura popular de Brasil fue de forma natural desde temprana edad, a través de la Capoeira y la Samba, y posteriormente con el Forró. Participó en numerosos grupos artísticos y folclóricos de Minas Gerais, donde aprendió a valorar la cultura heredada y la importancia de transmitirla.',
  elton_p1: 'Su genialidad no es fruto de la casualidad. Su formación profesional en Forró, Capoeira y Samba se realizó a través del Instituto Sociocultural Grupo Ginga y la Universidad Estácio de Sá, donde cursó estudios en Educación Física, recibiendo formación universitaria en las disciplinas de Danza y Música, forjando así a un bailarín y mentor incomparable.',
  elton_p2: 'Inicios en el Forró: Simultáneamente, en el Grupo Ginga de Belo Horizonte, se inició un proyecto de Forró el 12 de abril de 2003, denominado “Pé Descalço”. En 2006, Elton comenzó su formación universitaria, donde perfeccionó sus habilidades didácticas e incorporó más herramientas en su proceso formativo. Recibió gran parte de sus enseñanzas y conocimientos de sus mentores Rick, Lucas y César, hasta marzo de 2008.',
  elton_p3: 'En 2008, Elton se mudó a Europa y estableció su residencia en Sevilla, España, en 2010. Fue entonces cuando inició un proyecto pionero de integración cultural con elementos de la cultura popular de Brasil. Desde entonces, forma parte fundamental de la escena cultural brasileña en Sevilla, impartiendo clases regulares magistrales en distintos lugares de España y Europa, y participando en varios festivales.',
  elton_p4: 'Actualmente, Elton es el organizador y mentor del proyecto Forró Arrastapé Sevilla, en el cual trabaja principalmente los estilos de Forró Tradicional y Universitario. Su método de enseñanza es único y magistral, influenciado por la danza de salón pero fundamentado en las bases del Forró de Luiz Gonzaga.',
  elton_p5: 'El inconfundible estilo de Forró Arrastapé se caracteriza por una espectacular combinación de movimientos básicos y acrobáticos, donde el bailarín, una vez que aprende la base, puede y debe buscar sus propias formas de expresión, improvisar y crear sus propios movimientos con total libertad.',
  elton_quote: 'Según el propio Profesor Elton: "El baile tiene que ser lúdico y placentero, alegre y divertido, proporcionando a la gente la libertad de expresión y la transformación del propio ser, siendo espontáneo, de auto-superación, unido a la consolidación de nuevas amistades y mejorando el entorno social".',
  elton_gallery_title: 'Momentos Destacados'
} as const;

export default history;
